/** Declaration file generated by dts-gen */

export class Facebook {
    constructor(opts: any, _internalInherit: any);

}

export const version: string;

export function FacebookApiException(res: any): void;

export function api(): any;

export function extend(p0: any): any;

export function getAccessToken(): any;

export function getLoginUrl(): any;

export function napi(): any;

export function options(p0: any): any;

export function parseSignedRequest(p0: any): any;

export function setAccessToken(p0: any): any;

export function withAccessToken(p0: any): any;

export namespace FB {
    function api(): any;

    function extend(p0: any): any;

    function getAccessToken(): any;

    function getLoginUrl(): any;

    function napi(): any;

    function options(p0: any): any;

    function parseSignedRequest(p0: any): any;

    function setAccessToken(p0: any): any;

    function withAccessToken(p0: any): any;

}

